name: 'GitHub Actions'
 
on:
  push:
  schedule:
  # 定时任务，在每天的7点
    - cron: '0 23 * * *'

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
    # 首先copy git仓库到虚拟机上
      - name: 'Checkout codes'
        uses: actions/checkout@v1
        with:
            python-version: 3.7
    # 执行仓库中的脚本文件
      - name: 'sign in'
        run: |
             ping ehall.jlu.edu.cn
             python -m pip install --upgrade pip
             pip install requests
             pip install beautifulsoup4
             python ./user.py
             
